# Generated by Django 3.0.4 on 2020-03-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import staff.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('High Level', 'High Level'), ('Mid Level', 'Mid Level'), ('Low Level', 'Low Level')], default='Low Level', max_length=100, verbose_name='Role')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True, verbose_name='gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('posting', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posting')),
                ('insurance_cover', models.IntegerField(blank=True, null=True, verbose_name='Insurance Cover')),
                ('image', models.ImageField(blank=True, null=True, upload_to=staff.utils.upload_image_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_staff', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ['-created_at'],
            },
        ),
    ]
