# Generated by Django 3.0.4 on 2020-03-18 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import staff.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('posting', models.CharField(max_length=100, verbose_name='Posting')),
                ('insurance_cover', models.IntegerField(blank=True, null=True, verbose_name='Insurance Cover')),
                ('image', models.ImageField(blank=True, null=True, upload_to=staff.utils.upload_image_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_staff', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ['-created_at'],
            },
        ),
    ]
