# Generated by Django 3.0.4 on 2020-03-19 19:38

import animal.utils
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'HealthPoint',
                'verbose_name_plural': 'HealthPoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(max_length=100, verbose_name='Kingdom')),
                ('phylum', models.CharField(max_length=100, verbose_name='Phylum')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('order', models.CharField(max_length=100, verbose_name='Order')),
                ('family', models.CharField(max_length=100, verbose_name='Family')),
                ('genus', models.CharField(max_length=100, verbose_name='Genus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Specieses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('animal_type', models.CharField(choices=[('Invertebrates', 'Invertebrates'), ('Fish', 'Fish'), ('Amphibians', 'Amphibians'), ('Reptiles', 'Reptiles'), ('Birds', 'BIRDS'), ('Mammals', 'Mammals')], max_length=100, verbose_name='Animal Type')),
                ('colour', models.CharField(max_length=100, verbose_name='Colour')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Weight')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=animal.utils.upload_image_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_cage', to='maintenance.Cage', verbose_name='Cage')),
                ('health_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_health_point', to='animal.HealthPoint', verbose_name='Health Point')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_species', to='animal.Species', verbose_name='Species')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'ordering': ['-created_at'],
            },
        ),
    ]
