# Generated by Django 3.0.4 on 2020-03-27 05:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Weight (kg)'),
        ),
    ]
