# Generated by Django 3.0.4 on 2020-05-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_animalcage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalCage',
        ),
    ]
