# Generated by Django 3.0.4 on 2020-05-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_animalcage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cage',
        ),
    ]
