# Generated by Django 3.0.4 on 2020-03-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentset',
            name='equipments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_set_equipment', to='maintenance.Equipment', verbose_name='Equipments'),
        ),
    ]
