# Generated by Django 3.0.4 on 2020-03-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200319_2135'),
        ('maintenance', '0003_auto_20200322_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='equipment_set',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment_set',
            field=models.ManyToManyField(related_name='maintenence_equipment_set', to='maintenance.EquipmentSet', verbose_name='Equipment Set'),
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='staff',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='staff',
            field=models.ManyToManyField(related_name='staff_maintenance', to='staff.Staff', verbose_name='Staff'),
        ),
    ]
