# Generated by Django 3.0.4 on 2020-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20200323_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
