# Generated by Django 3.0.4 on 2020-03-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200319_2135'),
        ('maintenance', '0007_auto_20200323_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='staff',
        ),
        migrations.AddField(
            model_name='incident',
            name='staff',
            field=models.ManyToManyField(related_name='staff_incident', to='staff.Staff', verbose_name='Staff'),
        ),
    ]
