# Generated by Django 3.0.4 on 2020-03-27 05:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_auto_20200325_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Height (feet)'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Length (feet)'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Width (feet)'),
        ),
    ]
