# Generated by Django 3.0.4 on 2020-03-19 19:38

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('staff', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('composition', models.CharField(max_length=100, verbose_name='Composition')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_disease', to='animal.Animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_treatment_disease', to='health.Medicine', verbose_name='Disease')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_treatment_medicine', to='health.Medicine', verbose_name='Medicine')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_treatment_staff', to='staff.Staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'AnimalTreatment',
                'verbose_name_plural': 'AnimalTreatments',
                'ordering': ['-created_at'],
            },
        ),
    ]
