# Generated by Django 3.0.4 on 2020-03-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltreatment',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_treatment_disease', to='health.Disease', verbose_name='Disease'),
        ),
    ]
