# Generated by Django 3.0.4 on 2020-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200319_2135'),
        ('health', '0002_auto_20200327_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltreatment',
            name='medicine',
        ),
        migrations.AddField(
            model_name='animaltreatment',
            name='medicine',
            field=models.ManyToManyField(related_name='animal_treatment_medicine', to='health.Medicine', verbose_name='Medicine'),
        ),
        migrations.RemoveField(
            model_name='animaltreatment',
            name='staff',
        ),
        migrations.AddField(
            model_name='animaltreatment',
            name='staff',
            field=models.ManyToManyField(related_name='animal_treatment_staff', to='staff.Staff', verbose_name='Staff'),
        ),
    ]
