# Generated by Django 3.0.4 on 2020-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20200504_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltreatment',
            name='recovered',
            field=models.CharField(choices=[('Recovered', 'Recovered'), ('Not Recovered', 'Not Recovered')], default='Not Recovered', max_length=50, verbose_name='Recovered'),
        ),
    ]
