# Generated by Django 3.0.4 on 2020-03-27 04:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200327_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfood',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity'),
        ),
    ]
