# Generated by Django 3.0.4 on 2020-03-27 05:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200327_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfood',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity (kg)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Carbohydrate (gm)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fat (gm)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='mineral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mineral (gm)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Protein (gm)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vitamin (gm)'),
        ),
    ]
